service: owl
plugins:
  - serverless-s3-sync
  - serverless-cloudformation-sub-variables
  # - serverless-esbuild
  # - serverless-cloudside-plugin

custom:
  stage: ${opt:stage, 'dev'}
  # Add your own domain here
  Domains:
    default: ${self:custom.stage}.serverlessowl.dev
    production: serverlessowl.dev
  Domain: ${self:custom.Domains.${self:custom.stage}, self:custom.Domains.default}
  s3Sync:
    - bucketName: ${self:service}-${self:custom.stage}-website
      localDir: build
      defaultContentType: text/html
      acl: public-read

provider:
  name: aws
  timeout: 30
  memorySize: 1024
  runtime: nodejs12.x
  profile: personal
  region: eu-west-1
  stage: ${self:custom.stage}

resources:
  # Cognito Resources
  # - ${file(./infrastructure/authentication/UserPool.yml)}
  # - ${file(./infrastructure/authentication/UserPoolClient.yml)}
  # - ${file(./infrastructure/authentication/HostedUi.yml)}
  # - ${file(./infrastructure/authentication/IdentityPool.yml)}
  # - ${file(./infrastructure/authentication/CognitoAuthorizedRole.yml)}
  # - ${file(./infrastructure/authentication/IdentityRoleMapping.yml)}

  # Database Resources
  # - ${file(./infrastructure/database/Dynamo.yml)}

  # Gateway Resources
  - ${file(./infrastructure/gateway/Distribution.yml)}
  - ${file(./infrastructure/gateway/RecordSets.yml)}

  # Website Resources
  - ${file(./infrastructure/website/Bucket.yml)}
