service: sfea

plugins:
  - serverless-s3-sync
  # - serverless-esbuild
  # - serverless-cloudside-plugin

custom:
  # Add your own domain here
  Domain: example.com
  s3Sync:
    - bucketName:
        Ref: WebsiteBucket
      localDir: build

provider:
  name: aws
  timeout: 30
  memorySize: 1024
  runtime: nodejs12.x

resources:
  # Cognito Resources
  - ${file(./infrastructure/authentication/UserPool.yml)}
  - ${file(./infrastructure/authentication/UserPoolClient.yml)}
  - ${file(./infrastructure/authentication/HostedUi.yml)}
  - ${file(./infrastructure/authentication/IdentityPool.yml)}
  - ${file(./infrastructure/authentication/CognitoAuthorizedRole.yml)}
  - ${file(./infrastructure/authentication/IdentityRoleMapping.yml)}

  # Database Resources
  - ${file(./infrastructure/database/Dynamo.yml)}

  # Gateway Resources
  - ${file(./infrastructure/gateway/Certificate.yml)}
  - ${file(./infrastructure/gateway/Distribution.yml)}
  - ${file(./infrastructure/gateway/HostedZone.yml)}
  - ${file(./infrastructure/gateway/RecordSet.yml)}

  # Website Resources
  - ${file(./infrastructure/website/Bucket.yml)}
