# Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpooldomain.html
Resources:
  HostedUi:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: ${self:service}-${opt:stage}
      UserPoolId: "#{UserPool}"
