# Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html
Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - "dev.serverlessowl.dev"
        IPV6Enabled: true
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:260235234243:certificate/ad674a44-e633-4208-98f3-7a85f842eef9
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          TargetOriginId: WebApp
          ViewerProtocolPolicy: "redirect-to-https"
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
        Enabled: true
        Origins:
          - Id: WebApp
            DomainName: ${self:service}-${self:custom.stage}-website.s3-website-eu-west-1.amazonaws.com
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
