# Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html
Resources:
  DNSRecordIPV4:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Ref: DNS
      Name: ${self:custom.Domain}
      TTL: "900"
      Type: A
  DNSRecordIPV6:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Ref: DNS
      Name: ${self:custom.Domain}
      TTL: "900"
      Type: AAAA
