# Docs https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-resolver.html
Resources:
  MutationaddTodoResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: Schema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Mutation
      FieldName: addTodo
      DataSourceName: !GetAtt DataSource.Name
      RequestMappingTemplate: |
        #set( $d = $util.dynamodb )
        #set( $values = $d.toMapValues($ctx.args))
        {
            "version" : "2017-02-28",
            "operation" : "PutItem",
            "key" : {
                "pk" : $d.toDynamoDBJson($ctx.args.id),
                "sk" : $d.toDynamoDBJson($ctx.args.name)
            },
            "attributeValues" : $util.toJson($values),
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"
