# Docs https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-resolver.html
Resources:
  MutationgetTodoResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: Schema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Query
      FieldName: getTodos
      DataSourceName: !GetAtt DataSource.Name
      RequestMappingTemplate: |
        {
            "version" : "2017-02-28",
            "operation" : "Query",
            "query" : {
                "expression": "pk = :pk",
                "expressionValues" : {
                    ":pk" : $util.dynamodb.toDynamoDBJson($ctx.args.id)
                }
            }
        }
      ResponseMappingTemplate: |
        {
            "data": "$utils.toJson($ctx.result.items)"
        }
