# Docs https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:service}-${self:custom.stage}-website
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      AccelerateConfiguration:
        AccelerationStatus: Enabled
