# Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html
Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - ${self:custom.Domain}
        IPV6Enabled: true
        PriceClass: PriceClass_100
        HttpVersion: http2
        ViewerCertificate:
          AcmCertificateArn: ${self:custom.CertArn}
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          TargetOriginId: WebApp
          ViewerProtocolPolicy: "redirect-to-https"
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          AllowedMethods:
            - GET
            - HEAD
        CacheBehaviors:
          - TargetOriginId: OwlApi
            ViewerProtocolPolicy: redirect-to-https
            PathPattern: /api*
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
        Enabled: true
        Origins:
          - Id: WebApp
            DomainName: "#{WebsiteBucket}.s3-website-eu-west-1.amazonaws.com"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
          - Id: OwlApi
            DomainName: "#{HttpApi}.execute-api.eu-west-1.amazonaws.com"
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
Outputs:
  CloudFrontDistribution:
    Value: !Ref CloudFrontDistribution
