# Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html
Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - ${self:custom.Domain}
        IPV6Enabled: true
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: ${ssm:/aws/reference/secretsmanager/owl/certificate/arn~true}
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          TargetOriginId: WebApp
          ViewerProtocolPolicy: "redirect-to-https"
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
        Enabled: true
        Origins:
          - Id: WebApp
            DomainName: "#{WebsiteBucket}.s3-website-eu-west-1.amazonaws.com"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
